### ISSUE TITLE
Why escaping attribute in some case?

### ISSUE THREAD

**Issue by ruiming** [stackia/test2doc.js#2]
I found that you escapes some keyword such as 'Sample', 'Item'. Why?
It cause a different appearance in some word when it is surrounded by the **`**.
```
+ Response 200 (application/json)

    + Attributes
        + success: true (boolean)
        + data (array)
            + (object)
                + id: 320000201201067240
                + title: aaa
                + type: hlufp
                + input: aaa
                + output: aaa
                + `sampleInput`: aaa
                + `sampleOutput`: aaa
                + inputData: aaa
                + outputData: aaa
                + submitCount: 10 (number)
                + takeCount: 4 (number)
                + userId: 13000020131004478X
```

**Comment by stackia** [comment]
MSON reserved keywords:
https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#6-reserved-characters--keywords

But the specification doesn't say if we should check equality or inclusion relationship. Maybe we should check inclusion relationship on reserved characters and equality on reserved keywords.

**Comment by stackia** [comment]
I have changed the way to escape these keywords to `haystack.include(needle)` on reserved characters and `haystack === needle` on reserved keywords.
https://github.com/stackia/test2doc.js/commit/82c3e59d7a52f1375dfbfd0f1ac2a75f65397b09
