### ISSUE TITLE
How to aggregate swagger files that were generated on different tests?

### ISSUE THREAD

**Issue by ducky-hong** [stackia/test2doc.js#4]
My tests are located next to source files like this.

```
src
|___user
      |___user.js
      |___router.js
      |___router.test.js
```

I have multiple test files that generate swagger spec files using test2doc. But how to combine all swagger files into one? Since swagger-ui only takes one swagger file, I need to make them into single file.

As a dirty fix, I write each swagger spec into one file and merge with newly generated spec. My jest setup is like this. Please beware I am new to the javascript land.

```js
function generateSwaggerFile() {
  const generated = JSON.parse(doc.emit(null, 'swagger', { useYaml: false }));
  const intermediate = JSON.parse(fs.readFileSync('swagger.json', 'utf8'));
  const merged = deepmerge(intermediate, generated);
  fs.writeFileSync('swagger.json', JSON.stringify(merged));
}

afterAll(() => {
  generateSwaggerFile();
});
```

Is there any better way handle this use case?

Thanks.

**Comment by stackia** [comment]
You can try to run `doc.emit()` in another separate global test setup file.

For example, if you are using mocha.js

setup.test.js
```
const doc = require('test2doc')

after(function () {
  doc.emit('swagger.json', 'swagger')
})
```

Then run your test with `mocha setup.test.js router.test.js xxx.test.js`.

Try to call `doc.emit()` at the last stage where all test have passed to make sure it collects all the information in every test files.

**Comment by ducky-hong** [comment]
My code snippet is in a global setup file.

I use Jest for a test runner, but as far as I know, `after` hook is called for every test file. That is, if there are two test files `a.test.js` and `b.test.js`, then `doc.emit` is called twice and it overwrites a previous swagger file.

**Comment by stackia** [comment]
Seems Jest doesn't provide a built-in way to run some code after all test files. Here is a workround:

generate-swagger.spec.js
```javascript
describe('generate swagger', () => {
  require('require-glob').sync('*.test.js')
})

afterAll(() => {
  doc.emit('swagger.json', 'swagger')
})
```

Then run `jest generate-swagger.spec.js` to run all tests and generate swagger.json.

**Comment by ducky-hong** [comment]
It works like a charm! Thank you.
